name: Ruff + Mypy + Hassfest

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: lint-type-hassfest-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ruff:
    name: Ruff Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"   # Alineado con HA actual
          cache: "pip"
      - run: pip install "ruff==0.6.5"
      - name: Run Ruff
        run: ruff check custom_components/media_downloader/

  mypy:
    name: Mypy Type Check
    runs-on: ubuntu-latest
    env:
      MYPYPATH: .
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"
      - name: Install mypy + stubs
        run: |
          pip install "mypy==1.10.*" types-setuptools types-pyyaml types-requests
      - name: Run Mypy
        run: mypy --config-file mypy.ini

  hassfest:
    name: Hassfest Validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: home-assistant/actions/hassfest@master
